# Generated by Django 5.0.1 on 2024-03-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NotAmazon', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
